### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by 8kbh** [Rtif173/flashcards-vue#1]
- Learn page
  - [x] result info
  - [ ] previous and shuffle button
  - Card
    - [ ] swipe control
    - [ ] edit card
    - [ ] counter
- Files page
  - [ ] delete file
  - [ ] change file name if there is another file with the same name
  - [ ] delete card
- MatkdownW
  - Components
    - [ ] A
    - [ ] BlockQuote
    - [ ] Code
    - [ ] CodeInline
    - [x] Em
    - [x] H1-H6
    - [ ] Hr
    - [x] Img
    - [ ] Li
    - [ ] Ol
    - [x] P
    - [x] Strong
    - [ ] Table
    - [ ] Tbody
    - [ ] Td
    - [ ] Th
    - [ ] Thead
    - [ ] Tr
    - [ ] Ul
- Logic
  - [ ] info about bad result of process of creating cards
  - [ ] import/export json
  - [ ] local storage
  - [ ] google drive
  - [ ] preview for associated cards (links in md)

**Comment by 8kbh** [comment]
# Bug

- [x] ~editor~
